---
- name: install java and tomcat packages
  apt: pkg={{ item }} state=installed
  sudo: true
  with_items:
   - openjdk-7-jre
   - tomcat6
   - tomcat6-extras
   - tomcat6-admin

- name: change port of tomcat server
  copy: src=server.xml dest=/etc/tomcat6/server.xml
  sudo: true

- name: ensure correct run level of tomcat
  service: name=tomcat6 enabled=yes
  sudo: true
  notify:
   - restart tomcat6

- name: force (re)start of tomcat6
  service: name=tomcat6 state=restarted
  sudo: true

- name: copy the tomcat6 users file
  copy: src=tomcat-users.xml dest=/etc/tomcat6/tomcat-users.xml owner=tomcat6 group=tomcat6 mode=0644
  sudo: true
  notify:
   - restart tomcat6

- name: get iptables rules
  shell: iptables -L
  register: iptablesrules
  always_run: yes
  sudo: true
  changed_when: false

- name: add tomcat iptable rule
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8081 -j ACCEPT -m comment --comment "tomcat"
  sudo: true
  when: iptablesrules.stdout.find("tomcat") == -1
  notify:
   - save iptables

- name: download apache commons logging
  command: wget http://mirrors.ukfast.co.uk/sites/ftp.apache.org/commons/logging/binaries/commons-logging-1.2-bin.tar.gz chdir=/home/{{ user }} creates=/home/{{ user }}/commons-logging-1.2-bin.tar.gz

- name: extract apache commons logging
  command: tar -zxf commons-logging-1.2-bin.tar.gz chdir=/home/{{ user }} creates=/home/{{ user }}/commons-logging-1.2
  sudo: true

- name: list commons-logging files (in order to copy)
  command: ls -1 /home/{{ user }}/commons-logging-1.2/
  register: commonsfiles

- name: copy apache commons logging
  command: cp -r /home/{{ user }}/commons-logging-1.2/{{ item }} /usr/share/tomcat6/lib creates=/usr/share/tomcat6/lib/{{ item }}
  sudo: true
  with_items: commonsfiles.stdout_lines

- name: download SLF4J
  command: wget http://www.slf4j.org/dist/slf4j-1.7.7.tar.gz chdir=/home/{{ user }} creates=/home/{{ user }}/slf4j-1.7.7.tar.gz

- name: extract SLF4J
  command: tar -zxf slf4j-1.7.7.tar.gz chdir=/home/{{ user }} creates=/home/{{ user }}/slf4j-1.7.7

- name: list slf4j files (in order to copy)
  command: ls -1 /home/{{ user }}/slf4j-1.7.7/
  register: slf4jfiles

- name: copy SLF4J
  command: cp -r /home/{{ user }}/slf4j-1.7.7/{{ item }} /usr/share/tomcat6/lib creates=/usr/share/tomcat6/lib/{{ item }}
  sudo: true
  with_items: slf4jfiles.stdout_lines
  when: "'android' not in item and 'slf4j-log4j12' not in item and 'log4j-over-slf4j' not in item and 'slf4j-jcl' not in item"

- name: force restart of tomcat6
  service: name=tomcat6 state=restarted
  sudo: true

- name: copy the log4j properties file
  copy: src=log4j.properties dest=/usr/share/tomcat6/lib/log4j.properties
  sudo: true
